/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hopital.Patients;
import Hopital.myConnection;


import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author Badr
 */
public class listePatients extends javax.swing.JFrame {

    /**
     * Creates new form ListePatientss
     */
    public listePatients() {
        initComponents();
       jTable1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 40));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 1120, 190));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/Close.png"))); // NOI18N
        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 39)); // NOI18N
        jLabel1.setText("Liste Patients");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 300, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Entrer cin ou nom :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 210, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/print.png"))); // NOI18N
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/liste-de-papier.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/waves.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 1130, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        String rech=jTextField1.getText();
        try {

            Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from patient where nom LIKE '%" + rech + "%' OR cin LIKE '%" + rech + "%'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Aucun données affichée");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try {
            if (jTable1.getRowCount()!=0) {
            PdfWriter.getInstance(doc,new FileOutputStream("ListePatients.pdf"));
            doc.open();

            Font fontbold1 = FontFactory.getFont("Times-Roman", 15,Font.UNDERLINE);
            Paragraph title = new Paragraph("Liste des patients",fontbold1);
            title.setAlignment(Paragraph.ALIGN_CENTER);
            doc.add(title);
            /*
            Image img = Image.getInstance("examination.png");
            img.setAbsolutePosition(0 , 0);
            img.scaleToFit(300 , 109);
            doc.add(img);
            */

            Paragraph line = new Paragraph("\n\n");
            doc.add(line);
            Font fontbold2 = FontFactory.getFont("Times-Roman", 12,Font.BOLD);
            Font fontbold3 = FontFactory.getFont("Times-Roman", 12,Font.NORMAL);
            PdfPTable tbl=new PdfPTable(7);
            //tbl.setHorizontalAlignment(Element.ALIGN_CENTER);
            tbl.addCell(new Phrase("Id",fontbold2));
            tbl.addCell(new Phrase("Cin",fontbold2));
            tbl.addCell(new Phrase("Nom",fontbold2));
            tbl.addCell(new Phrase("Prenom",fontbold2));
            tbl.addCell(new Phrase("Téléphone",fontbold2));
            tbl.addCell(new Phrase("Sex",fontbold2));
            tbl.addCell(new Phrase("Adresse",fontbold2));
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String id=jTable1.getValueAt(i, 0).toString();
                String c=jTable1.getValueAt(i, 1).toString();
                String n=jTable1.getValueAt(i, 2).toString();
                String p=jTable1.getValueAt(i, 3).toString();
                String t=jTable1.getValueAt(i, 4).toString();
                String s=jTable1.getValueAt(i, 5).toString();
                String a=jTable1.getValueAt(i, 6).toString();

                tbl.addCell(new Phrase(id,fontbold3));
                tbl.addCell(new Phrase(c,fontbold3));
                tbl.addCell(new Phrase(n,fontbold3));
                tbl.addCell(new Phrase(p,fontbold3));
                tbl.addCell(new Phrase(t,fontbold3));
                tbl.addCell(new Phrase(s,fontbold3));
                tbl.addCell(new Phrase(a,fontbold3));
                float[] columnWidths = new float[]{8f, 18f, 20f, 20f,22f,15f,30f};
                tbl.setWidths(columnWidths);

            }
            doc.add(tbl);
            doc.close();
              
                        JOptionPane.showMessageDialog(null,"La liste des patients est bien générée");
            }
                          else{
                             JOptionPane.showMessageDialog(null,"aucune donnée à affichée");
                       }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
                           try {
            java.sql.Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            ResultSet rs=stm.executeQuery("select cin as Cin,nom as Nom,prenom as Prénom,telephone as Téléphone,sex as Sex,adresse as Adresse from patient");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listePatients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listePatients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
