/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hopital.Patients;
import Hopital.myConnection;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Badr
 */
public class ModifierPatient extends javax.swing.JFrame {

    /**
     * Creates new form AjouterNouveauPatient
     */
    public ModifierPatient() {
        initComponents();
    jId.setVisible(false);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCin = new javax.swing.JTextField();
        jNom = new javax.swing.JTextField();
        jPrenom = new javax.swing.JTextField();
        jTel = new javax.swing.JTextField();
        jAdresse = new javax.swing.JTextField();
        jSex = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jrech = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Téléphone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sex");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Adresse");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jCin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 205, -1));

        jNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomActionPerformed(evt);
            }
        });
        getContentPane().add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 205, -1));

        jPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 205, -1));

        jTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 205, -1));

        jAdresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdresseActionPerformed(evt);
            }
        });
        getContentPane().add(jAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 205, -1));

        jSex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        getContentPane().add(jSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 205, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/save-icon--1.png"))); // NOI18N
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/Close.png"))); // NOI18N
        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/user.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setText("Éditer Patient");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 270, 70));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Rechercher par cin ou nom");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 23));

        Jrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JrechKeyPressed(evt);
            }
        });
        getContentPane().add(Jrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 205, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/remove-user (1).png"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 140, 40));
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/waves.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     int id =Integer.parseInt(jId.getText());   
   String cin=jCin.getText();
        String nom=jNom.getText();
        String prenom=jPrenom.getText();
        String telephone=jTel.getText();
        String sex=(String)jSex.getSelectedItem();
        String adresse=jAdresse.getText();
        try {
            Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            stm.executeUpdate("update patient set cin='"+cin+"',nom='"+nom+"',prenom='"+prenom+"',telephone='"+telephone+"',sex='"+sex+"',adresse='"+adresse+"' where ID='"+id+"'");
            JOptionPane.showMessageDialog(null, "La modification est bien faite");
            setVisible(false);
            new ModifierPatient().setVisible(true);
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"VerifieBH56r autre fois");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdresseActionPerformed

    private void JrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JrechKeyPressed
        // TODO add your handling code here:
        String rech=Jrech.getText();
        try {
            Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from patient where cin LIKE '%" + rech + "%' OR nom LIKE '%" + rech + "%'");

            if (rs.next()) {
                 jId.setText(rs.getString("ID"));
                jCin.setText(rs.getString("cin"));
                jNom.setText(rs.getString("nom"));
                jPrenom.setText(rs.getString("prenom"));
                jTel.setText(rs.getString("telephone"));
                jSex.setSelectedItem("sex");
                jAdresse.setText(rs.getString("adresse"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Aucun données affichée");
        }
    }//GEN-LAST:event_JrechKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            
         if ( jCin.getText().equals("") || jNom.getText().equals("")|| jPrenom.getText().equals("")|| jTel.getText().equals("")|| jAdresse.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Veuillez remplir les champs");}
         else{
        int a=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer ce patient ?","delete",JOptionPane.YES_OPTION);
        if (a==0) {
            try{

                Connection con=myConnection.getCon();
                Statement stm=con.createStatement();
                stm.executeUpdate("delete from patient where cin='"+jCin.getText()+"'");
                JOptionPane.showMessageDialog(null, "La suppression est bien faite");
                setVisible(false);
                new ModifierPatient().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jrech;
    private javax.swing.JTextField jAdresse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCin;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNom;
    private javax.swing.JTextField jPrenom;
    private javax.swing.JComboBox<String> jSex;
    private javax.swing.JTextField jTel;
    // End of variables declaration//GEN-END:variables
}
