/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hopital.Rdv;
import Hopital.myConnection;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Badr
 */
public class ReserverRdv extends javax.swing.JFrame {

    /**
     * Creates new form AjouterNouveauPatient
     */
    public ReserverRdv() {
        initComponents();
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCin = new javax.swing.JTextField();
        jNom = new javax.swing.JTextField();
        jPrenom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jHR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPrixVis = new javax.swing.JTextField();
        jDateR = new com.toedter.calendar.JDateChooser();
        jDateRet = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date Rendez-Vous");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Heure Rendez-Vous");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date Retour");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jCin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCinActionPerformed(evt);
            }
        });
        getContentPane().add(jCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 205, -1));

        jNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomActionPerformed(evt);
            }
        });
        getContentPane().add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 205, -1));

        jPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 205, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/save-icon--1.png"))); // NOI18N
        jButton1.setText("Sauvegerder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/Close.png"))); // NOI18N
        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 140, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/booking.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setText("Résérver Rendez-Vous");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 400, 70));

        jHR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jHR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 205, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Prix de visite");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jPrixVis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPrixVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrixVisActionPerformed(evt);
            }
        });
        getContentPane().add(jPrixVis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 205, -1));

        jDateR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jDateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 205, 210, 30));

        jDateRet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jDateRet, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 205, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/waves.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try {
           if ( jCin.getText().equals("") || jNom.getText().equals("")|| jPrenom.getText().equals("")||jDateR.getDate()==null|| jDateRet.getDate()==null||jPrixVis.getText().equals("")||jHR.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Veuillez remplir les champs");}
           else{  
        String cin=jCin.getText();
        String nom=jNom.getText();
        String prenom=jPrenom.getText();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
       String dateR = dateFormat1.format(jDateR.getDate());
        String heureR=jHR.getText();
       SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
       String dateRetour = dateFormat2.format(jDateRet.getDate());
        double prixVisite=Double.parseDouble(jPrixVis.getText());
        
  
             Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
             ResultSet rs= stm.executeQuery("select * from patient where cin='"+cin+"' AND nom='"+nom+"' AND prenom='"+prenom+"'");
               if (!rs.next()) {
        JOptionPane.showMessageDialog(null, "Cette personne n'existe pas");

            }
               else{
            stm.executeUpdate("insert into rdv(cin,nom,prenom,dateRdv,heureRdv,dateRetour,prixVisite)values('"+cin+"','"+nom+"','"+prenom+"','"+dateR+"','"+heureR+"','"+dateRetour+"','"+prixVisite+"')");
            JOptionPane.showMessageDialog(null, "La sauvegarde du rendez-vous est bien faite");
            setVisible(false);
            new ReserverRdv().setVisible(true);
               }  }} catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Essayez autre fois");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPrixVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrixVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrixVisActionPerformed

    private void jCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCinActionPerformed
        // TODO add your handling code here:
           String cin=jCin.getText();
        try {
            Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from patient where cin like'"+cin+"%'");
               if (rs.next()) {
                jCin.setText(rs.getString(1));
                jNom.setText(rs.getString(2));
                jPrenom.setText(rs.getString(3));
            }
            else{
               jCin.setText("");
                jNom.setText("");
                jPrenom.setText("");       }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Essayez autre fois");
        }
                                             

   
    }//GEN-LAST:event_jCinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserverRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserverRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserverRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserverRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserverRdv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCin;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateR;
    private com.toedter.calendar.JDateChooser jDateRet;
    private javax.swing.JTextField jHR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNom;
    private javax.swing.JTextField jPrenom;
    private javax.swing.JTextField jPrixVis;
    // End of variables declaration//GEN-END:variables
}
