/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hopital.Medicaments;
import Hopital.myConnection;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Badr
 */
public class ModifierMedicament extends javax.swing.JFrame {

    /**
     * Creates new form AjouterNouveauPatient
     */
    public ModifierMedicament() {
        initComponents();
        jDesc.setLineWrap(true);
        jId.setVisible(false);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDf = new com.toedter.calendar.JDateChooser();
        jDp = new com.toedter.calendar.JDateChooser();
        jqte = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Jrech = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nom Medicament");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date Fabrication");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date périmée");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantité");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 205, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/save-icon--1.png"))); // NOI18N
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/Close.png"))); // NOI18N
        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/follow(1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setText("Éditer Médicament");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 330, 70));

        jDf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jDf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 205, 28));

        jDp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 205, 28));

        jqte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jqte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 205, 28));

        jDesc.setColumns(20);
        jDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDesc.setRows(5);
        jScrollPane1.setViewportView(jDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Rechercher par nom");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 23));

        Jrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrechActionPerformed(evt);
            }
        });
        Jrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JrechKeyPressed(evt);
            }
        });
        getContentPane().add(Jrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 205, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/delete.png"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, 40));
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hopital/images/waves.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JrechKeyPressed
        // TODO add your handling code here:
        String rech=Jrech.getText();
        try {
            Connection con=myConnection.getCon();
            Statement stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from medicament where nom LIKE '%" + rech + "%'");

            if (rs.next()) {
                
                 jId.setText(rs.getString("ID"));
                jNom.setText(rs.getString("nom"));
            
               
               jDf.setDate(rs.getDate("dateF"));
               jDp.setDate(rs.getDate("dateP"));
      
                jqte.setValue(rs.getInt("qte"));
                jDesc.setText(rs.getString("description"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_JrechKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if ( jNom.getText().equals("") || jqte.getValue().equals("")||jDf.getDate()==null||jDp.getDate()==null) {
                JOptionPane.showMessageDialog(null, "Veuillez remplir les champs");
            }
            else{
                int id =Integer.parseInt(jId.getText());  
                String nom=jNom.getText();
                SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
                String Df=dateFormat1.format(jDf.getDate());
                SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
                String Dp=dateFormat2.format(jDp.getDate());
                int qte=(int) jqte.getValue();
                String desc=jDesc.getText();

                Connection con=myConnection.getCon();
                Statement stm=con.createStatement();
               stm.executeUpdate("update medicament set nom='"+nom+"',dateF='"+Df+"',dateP='"+Dp+"',qte='"+qte+"',description='"+desc+"' where ID='"+id+"'");
                JOptionPane.showMessageDialog(null, "La modification est bien ");
                setVisible(false);
                new ModifierMedicament().setVisible(true);
            }  } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JrechActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if ( jNom.getText().equals("") || jqte.getValue().equals("")||jDf.getDate()==null||jDp.getDate()==null) {
          JOptionPane.showMessageDialog(null, "Veuillez remplir les champs");
            }
        else{
            int a=JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment supprimer ce medicament ?","delete",JOptionPane.YES_OPTION);
            if (a==0) {
                try{

                    Connection con=myConnection.getCon();
                    Statement stm=con.createStatement();
                    stm.executeUpdate("delete from medicament where nom='"+jNom.getText()+"'");
                    JOptionPane.showMessageDialog(null, "La suppression est bien faite");
                    setVisible(false);
                    new ModifierMedicament().setVisible(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierMedicament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jrech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jDesc;
    private com.toedter.calendar.JDateChooser jDf;
    private com.toedter.calendar.JDateChooser jDp;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jqte;
    // End of variables declaration//GEN-END:variables
}
